sdss/valis

CHANGELOG.rst, poetry.lock, pyproject.toml, python/valis/db/models.py, python/valis/db/queries.py, python/valis/io/model_spectra_info.json, python/valis/io/spectra.py, python/valis/routes/files.py, python/valis/routes/query.py, python/valis/routes/target.py, python/valis/utils/paths.py, python/valis/utils/versions.py
Adds a new endpoint at `/valis/target/ids/{sdss_id}` for getting object pipeline metadata for an sdss_id.  For now this works only for BHM until we can get the Astra ORM in sdssdb.  Apogee can't yet be integrated until Astra, since `apogee_drp` does not include the `sdss_id`.     
This also adds a POC endpoint for getting a spectrum from a file on disk, given an sdss_id.  Also only for BHM spec and spec-lite files.  
Additionally includes some minor tweaks for readability, and a first pass at switching some of the Query, and Path parameters to the new, recommended, `Annotated` way.  See https://fastapi.tiangolo.com/tutorial/query-params-str-validations/?h=#add-query-to-annotated-in-the-q-parameter and https://fastapi.tiangolo.com/tutorial/path-params-numeric-validations/#better-with-annota …
=> Adds new endpoint for getting target metadata and spectrum

python/valis/db/models.py, python/valis/db/queries.py, python/valis/routes/info.py
Adds a new valis endpoint at `/valis/info/database` to retrieve the `sdss5db` database metadata from the `vizdb.db_metadata` table.  This endpoint provides the descriptions of all the database columns.
=> Adds new route for database metadata

python/valis/db/queries.py, python/valis/routes/query.py
This adds the feature to return the list of targets with spectra at some observatory. Currently the query works by specifying a data release, an observatory and an instrument.
For just searching on BOSS or APOGEE spectra, the queries seem optimized enough I think (~4.5 sec for BOSS and ~2 sec for APOGEE at APO). Doing the union of both instruments takes much longer (~45 sec). The bottleneck here seems to be sequential scanning from looking at the query plan. I tried to turn this off and test it again, but the query plan says it still uses sequential scanning even after doing this. So, I am unsure what do do about this bit of the feature.
=> Return targets with spectra by observatory

python/valis/db/queries.py, python/valis/routes/query.py
This PR adds a new post request endpoint to get targets by a list of sdss_ids, using a body parameter.  This is for when we add support for uploading a file to the front end.   Updates the `get_targets_by_sdss_id` endpoint to accept a list of sdss_ids.
=> Added target_by_sdss_id_list endpoint

poetry.lock, pyproject.toml, python/valis/db/db.py, python/valis/db/models.py, python/valis/db/queries.py, python/valis/io/model_spectra_info.json, python/valis/io/spectra.py, python/valis/routes/info.py, python/valis/routes/query.py, python/valis/routes/target.py, python/valis/utils/paths.py, tests/test_utils.py
This PR adds support getting pipeline metadata for apogee and astra, using the astra and apogee ORMs, along with the associated spectra filepaths and/or the spectral data.  This PR only includes support for apStar and mwmStar files.
=> Adds support for apStar and mwmStar files 

README.md, poetry.lock, pyproject.toml, python/valis/routes/files.py
This PR moves the `sdss-solara` dependency, which includes the `sdss-explorer` dataview dashboard dependency to poetry's extras.  Running `poetry install` will now install just the valis stuff.  Running `poetry install -E solara` will install the extra solara dependencies for full development and testing.
=> moving solara dep to extras

python/valis/db/queries.py, python/valis/routes/query.py
Fixes #20
Modifies `carton_program_search` to appenth the carton/program filter to an input query. The `query/main` route backend now sends the initial query (cone search or sdss_id-based) to `carton_program_search`.
I think this is ready for review, but while testing this against the `pipelines` DB I found some inconsistencies that I don't understand. I'll add them here but this may be a different issue/bug.
If I do a request to `/query/main` with parameters
```json
{
"ra": 315.01417,
"dec": 45.299,
"radius": 0.1,
"units": "degree",
"id": 23326,
"program": "mwm_gg"
}
```
I get the following response
```json
{
"status": "success",
"msg": "data successfully retrieved",
"data": [
{
"sdss_id": 68024942,
"ra_sdss_id": 315.05084411121544,
"dec_sdss_id": 45.20588033521532,
"catalogid21": …
```
=> Modify carton_program_search to accept initial query

poetry.lock, pyproject.toml
Updates sdssdb to 0.12.0 which includes the double underscore separating tablename and PK in the column names in `sdss_id_to_catalog`.
It should also reflect tables much faster.
=> (chore): bump sdssdb to 0.12.0

CHANGELOG.rst, python/valis/db/models.py, python/valis/db/queries.py, python/valis/routes/query.py
This PR closes #29.  It updates the `append_pipes` query to also return the new `has_been_observed` column, and allows for filtering results based on the new column.  The default is set to True, to always filter for only observed targets.  It updates the cone search (`/query/cone`) endpoint and the main search (`/query/main`) endpoint, to use the new observed column. 
Currently requires the latest main of `sdssdb` to use.
=> Updates search endpoints to use the new observed column

CHANGELOG.rst, poetry.lock, pyproject.toml, python/valis/db/models.py, python/valis/db/queries.py, python/valis/routes/target.py
Implements a new endpoint `/target/parents/{catalog}/{sdss_id}` which returns parent catalog information for a given sdss_id. The response model is
> ~{~ 
>  ~"sdss_id": 129055990,~
>  ~"catalogid": 63050395068163877,~
>  ~"catalog": "gaia_dr3_source",~
>  ~"field_name": "source_id",~
>  ~"parent_catalog_id": 2605275489003187072~
> ~}~
~I'm not sure about the route name or the response contents or field names.~
```console
>> curl -L "http://127.0.0.1:8000/target/parents/gaia_dr3_source/129055990"            
{"sdss_id":129055990,"catalogid":63050395068163877,"source_id":2605275489003187072,"solution_id":1636148068921376768,"designation":"Gaia DR3 2605275489003187072","random_index":1020005880,"ref_epoch":2016.0,"ra":342.8413714603454,"ra_error":0.842067,"dec":-10.239850309221548,"dec_error …
```
=> Implement `/target/parents` endpoint

python/valis/routes/query.py
Adds a new `/query/list/parents` endpoint which returns the list of `catalogdb` tables that are referenced from `sdss_id_to_catalogs`.
```console
>> curl -L "http://127.0.0.1:8000/query/list/parents"                                                                              
["allstar_dr17_synspec_rev1","allwise","bhm_rm_v0","bhm_rm_v0_2","catwise","catwise2020","gaia_dr2_source","gaia_dr3_source","glimpse","guvcat","legacy_survey_dr10","legacy_survey_dr8","panstarrs1","ps1_g18","sdss_dr13_photoobj","skymapper_dr1_1","skymapper_dr2","supercosmos","tic_v8","twomass_psc","tycho2","unwise"]
```
Not sure about the `parents` segment of the route. I used `parents` to be symmetric with #38 but it could also be `catalogs`.
Closes #39.
=> Add `/query/list/parents` endpoint

python/valis/routes/mocs.py, tests/conftest.py, tests/test_mocs.py
This PR closes #27.   It updates the `moc` valis endpoints, and adds a new endpoint for listing the available MOCs, Multi-Ordered Coverage maps.  These are efficient sky footprint created from fits images or catalogs of sources.  These are created with either [MocPy](https://cds-astro.github.io/mocpy/index.html) or [Hipsgen-Cat](https://aladin.cds.unistra.fr/hips/HipsCat.gml#man).  `MocPy` only creates MOCs whereas `hipsgen-cat` creates both MOCs and HIPS catalogs.  
SDSS MOCs live at `$SDSS_HIPS` on the SAS, that points to `sas/sdsswork/sandbox/hips/`, organized by `{release}/{survey}`.  I've created MOCs and HIPS catalogs for the following surveys:
- IPL3 BHM
- DR17 manga
- DR17 mastar
- DR17 apogee
- DR17 eboss
The hips directory has been volume-mounted into the valis podman docker, …
=> Updating moc routes in valis

poetry.lock
This PR bumps the sdss-solara git commit to the latest to fold in changes from https://github.com/sdss/sdss_solara/pull/7, which addresses the smart y-scaling of Specviz.
=> Bumps the sdss-solara git hash

python/valis/db/models.py, python/valis/db/queries.py, python/valis/routes/info.py, python/valis/routes/query.py
This PR closes #52.  The `cone_search` query now outputs the separation distance between the input target and the search results.  The new `distance` parameter is attached to the common `SDSSModel` response, and made optional since other non-cone-search endpoints use the same response.    
Since this is a new return parameter not originally in the pipelines database, we also include a hack to insert metadata for this parameter into the `/info/database` endpoint.  This way the front-end can take advantage of it automatically with no code changes.
=> Adds separation distance to output of cone searches

poetry.lock, pyproject.toml, python/valis/db/models.py, python/valis/db/queries.py, python/valis/routes/info.py, python/valis/utils/paths.py
This PR closes #48, closes #45.  It updates the models and queries for the new `vizdb.sdssid_to_pipes` table schema, which includes the astra `release`: `dr17` or `sdss5`, and the `mjd` of data reduction.  It also exposes a new `in_bvs` field to indicate if the sdss_id is in the astra_050.boss_visit_spectrum table.  This will help differentiate from `in_boss`, which indicates if it's in the boss_drp.boss_spectrum table.
It also includes support for loading dr17 apStar files for sdss_ids that don't have MWM data.  This is necessary for astra reductions coming from dr17 apogee spectra and not MWM.
=> Support for astra dr17 spectra

python/valis/db/queries.py, python/valis/routes/query.py, python/valis/routes/target.py
This PR closes #53.  It adds a new endpoint `/target/sdssid/{id}` that allows to lookup a target sdss_id by an alternative id, like catalogid, the apogee id, or field-mjd-catalogid.    It returns the sdss id target info from the vizdb.sdss_id_stacked table, similar to the current main return query endpoint and the `target/id/{sdssid}` endpoint.   I minimally added just an sdssid lookup since I'm assuming users can follow-up with a query to the other sdssid-specific endpoints.  
It also updates the main query search form to accept an `altid` form field.  This is to support a future PR in zora to update the UI to add a new search field.  
It adds two new queries, `get_target_by_altid` and `get_sdssid_by_altid`.    The second performs the altid-to-sdssid lookup, using some clungy str/int …
=> Adds sdssid lookup using alternative id

python/valis/io/spectra.py
This is a bug fix for the `/target/spectra` where the array data from the file is not in the endian-ness of the native system.
=> Quick fix to the spectra byteorder

python/valis/db/queries.py, python/valis/routes/query.py
This PR changes the way that `append_pipes` runs to avoid the query planner making bad decisions when executing the query.
Currently `append_pipes` joins the pipelines tables to an existing query, extending its select. But in some cases this could make the query planner execute the query inefficiently. With this PR `append_to_queries` runs the initial query into a temporary table. Then it joins the temporary table to `sdssid_to_pipes`. This should never be less efficient than doing the whole things as a single query since joining to `sdssid_to_pipes` doesn't filter down any of the results from the original query, just adds columns.
With this the route
```
query/carton-program?name=manual_mwm_tess_ob&name_type=carton&observed=true&release=DR17
```
goes from taking about 13 seconds to 5 …
=> Prerun input query in `append_pipes`

python/valis/db/queries.py, python/valis/routes/query.py
This PR closes #49.  It adds a filter to the `append_pipes` method that filters down results based on the data release and the MJD cutoff for the given observatory.  
For releases less than DR17, we don't have a cutoff implemented yet, as these are different for different surveys.  See #71.  For all releases < DR17, it uses a MJD cutoff of 0 to effectively null the results, until we can properly support legacy data.
=> adding release filter for queries using the mjd cutoffs

python/valis/db/models.py, python/valis/db/queries.py
This PR adds a hack to remove LCO observations from query results.  This tacks on an additional where clause to the `append_pipes` method which filters on the astra fields `obs=apo` and `release=sdss5`.  This still includes LCO observations from DR17 processed by Astra.    The `append_pipes` method already includes a filter applying the MJD cutoff for a given release.  It currently gets used in the following endpoints:
- main search form (UI)
- cone search
- carton-program search
- target alternate id search
- target sdss id search
This is some but not all of the endpoints.   @Sean-Morrison can you take a look at this?  Is this a sufficient enough query to filter out the errant data?  And are these endpoints sufficient?
=> adding hack for lco bug fix

python/valis/db/queries.py, python/valis/routes/query.py, python/valis/routes/target.py, tests/test_utils.py
This PR adds a new API endpoint, `/query/altids` to search for targets by alternative id in bulk.  It adds a post request, similar to `/query/sdssid` that accepts a list of ids.  This is similar to `/target/sdssid/{id}/` to get a target by an alternative id.  
The post body accepts `alt_id_list` as a list of identifier names or ids, and `idtype` as a string indicating the type of integer id.  For integer ids, can specify `sdssid`, `catalogid`, or `gaiaid` (DR3).  
Effectively closes #59.  The file upload handling is now done by the zora front-end.
=> Adds new endpoint for bulk query by altid
